# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 17:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '\u0417\u0430\u0445\u043e\u0434\u0438',
            },
        ),
        migrations.CreateModel(
            name='tActProj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tActivities')),
            ],
            options={
                'verbose_name_plural': '\u041c\u0456\u0441\u0442 \u0417\u0430\u0445\u043e\u0434\u0438-\u041f\u0440\u043e\u0435\u043a\u0442\u0438',
            },
        ),
        migrations.CreateModel(
            name='tAddInfoInv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('url', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('file', models.FileField(default='', upload_to='files/investors/')),
            ],
            options={
                'verbose_name_plural': '\u0414\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0430 \u0456\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0456\u044f \u043f\u043e \u0456\u043d\u0432\u0435\u0441\u0442\u043e\u0440\u0430\u043c',
            },
        ),
        migrations.CreateModel(
            name='tAddInfoProj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('url', models.TextField(blank=True, default='', max_length=150, null=True)),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='files/projects/')),
            ],
            options={
                'verbose_name_plural': '\u0414\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0430 \u0456\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0456\u044f \u043f\u043e \u043f\u0440\u043e\u0435\u043a\u0442\u0430\u043c',
            },
        ),
        migrations.CreateModel(
            name='tDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('url', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('document', models.FileField(blank=True, default='', null=True, upload_to='files/docs/')),
            ],
            options={
                'verbose_name_plural': '\u0414\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0430 \u0456\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0456\u044f \u043f\u043e \u0441\u0442\u0430\u0440\u0442\u0430\u043f\u0435\u0440\u0430\u043c',
            },
        ),
        migrations.CreateModel(
            name='tInvestition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('type', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('res', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('sum', models.TextField(blank=True, default='', max_length=15, null=True)),
                ('descr', models.TextField(blank=True, default='', max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': '\u0406\u043d\u0432\u0435\u0441\u0442\u0438\u0446\u0456\u0457',
            },
        ),
        migrations.CreateModel(
            name='tInvestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('descr', models.TextField(blank=True, default='', max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': '\u0406\u043d\u0432\u0435\u0441\u0442\u043e\u0440\u0438',
            },
        ),
        migrations.CreateModel(
            name='tInvestorContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('surname', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('midname', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('phone', models.TextField(blank=True, default='', max_length=15, null=True)),
                ('mail', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('position', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('company', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('investorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tInvestor')),
            ],
            options={
                'verbose_name_plural': '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u0438 \u0456\u043d\u0432\u0435\u0441\u0442\u043e\u0440\u0456\u0432',
            },
        ),
        migrations.CreateModel(
            name='tKeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(blank=True, default='', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': '\u0422\u0435\u0433\u0438',
            },
        ),
        migrations.CreateModel(
            name='tKeyWordToProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '\u041c\u0456\u0441\u0442 \u0422\u0435\u0433\u0438-\u041f\u0440\u043e\u0435\u043a\u0442\u0438',
            },
        ),
        migrations.CreateModel(
            name='tMentoproj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '\u041c\u0456\u0441\u0442 \u041c\u0435\u043d\u0442\u043e\u0440\u0438-\u041f\u0440\u043e\u0435\u043a\u0442\u0438',
            },
        ),
        migrations.CreateModel(
            name='tMentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('surname', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('midname', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('phone', models.TextField(blank=True, default='', max_length=15, null=True)),
                ('mail', models.TextField(blank=True, default='', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': '\u041c\u0435\u043d\u0442\u043e\u0440\u0438',
            },
        ),
        migrations.CreateModel(
            name='tProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('sector', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('descr', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('type', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('isreal', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('financeScale', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('isactive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '\u041f\u0440\u043e\u0435\u043a\u0442\u0438',
            },
        ),
        migrations.CreateModel(
            name='tSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(blank=True, default='', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': '\u0428\u043a\u043e\u043b\u0438',
            },
        ),
        migrations.CreateModel(
            name='tStartuper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('surname', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('midname', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('phone', models.TextField(blank=True, default='', max_length=15, null=True)),
                ('mail', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('avatar', models.ImageField(blank=True, default='', null=True, upload_to='files/imgs/avatars/')),
                ('fgrade', models.BooleanField(default=False)),
                ('sgrade', models.BooleanField(default=False)),
                ('finyear', models.TextField(blank=True, default='-', max_length=5, null=True)),
                ('school', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tSchool')),
            ],
            options={
                'verbose_name_plural': '\u0421\u0442\u0430\u0440\u0442\u0430\u043f\u0435\u0440\u0438',
            },
        ),
        migrations.CreateModel(
            name='tStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('title', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tProject')),
            ],
            options={
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u0443\u0441\u0438',
            },
        ),
        migrations.CreateModel(
            name='tTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('islead', models.BooleanField(default=False)),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tProject')),
                ('startuperID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tStartuper')),
            ],
            options={
                'verbose_name_plural': '\u041c\u0456\u0441\u0442 \u0421\u0442\u0430\u0440\u0442\u0430\u043f\u0435\u0440\u0438-\u041f\u0440\u043e\u0435\u043a\u0442\u0438',
            },
        ),
        migrations.CreateModel(
            name='tUserSch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tSchool')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u0428\u043a\u043e\u043b\u0430',
                'verbose_name_plural': '\u0428\u043a\u043e\u043b\u0430',
            },
        ),
        migrations.CreateModel(
            name='tVisitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('investorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tInvestor')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tproject',
            name='school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tSchool'),
        ),
        migrations.AddField(
            model_name='tmentor',
            name='school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tSchool'),
        ),
        migrations.AddField(
            model_name='tmentoproj',
            name='mentorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tMentor'),
        ),
        migrations.AddField(
            model_name='tmentoproj',
            name='projectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tProject'),
        ),
        migrations.AddField(
            model_name='tkeywordtoproject',
            name='projectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tProject'),
        ),
        migrations.AddField(
            model_name='tkeywordtoproject',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tKeyWord'),
        ),
        migrations.AddField(
            model_name='tinvestor',
            name='school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tSchool'),
        ),
        migrations.AddField(
            model_name='tinvestor',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tinvestition',
            name='investorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tInvestor'),
        ),
        migrations.AddField(
            model_name='tinvestition',
            name='projectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tProject'),
        ),
        migrations.AddField(
            model_name='tdoc',
            name='startuperID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tStartuper'),
        ),
        migrations.AddField(
            model_name='taddinfoproj',
            name='projectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tProject'),
        ),
        migrations.AddField(
            model_name='taddinfoinv',
            name='investorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tInvestor'),
        ),
        migrations.AddField(
            model_name='tactproj',
            name='projectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tProject'),
        ),
        migrations.AddField(
            model_name='tactivities',
            name='school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tSchool'),
        ),
    ]
