# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Events',
            },
        ),
        migrations.CreateModel(
            name='tAddInfoInv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=50)),
                ('url', models.TextField(default='', max_length=50)),
                ('file', models.FileField(default='', upload_to='files/investors/')),
            ],
            options={
                'verbose_name': 'Investors additional info',
            },
        ),
        migrations.CreateModel(
            name='tAddInfoProj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=50)),
                ('url', models.TextField(default='', max_length=150)),
                ('file', models.FileField(default='', upload_to='files/projects/')),
            ],
            options={
                'verbose_name': 'Projects additional info',
            },
        ),
        migrations.CreateModel(
            name='tDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('url', models.TextField(default='', max_length=50)),
                ('document', models.FileField(default='', upload_to='files/docs/')),
            ],
            options={
                'verbose_name': 'Startuper documents',
            },
        ),
        migrations.CreateModel(
            name='tInvestition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.TextField(default='', max_length=50)),
                ('sum', models.TextField(default='', max_length=15)),
                ('descr', models.TextField(default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Investitions',
            },
        ),
        migrations.CreateModel(
            name='tInvestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor', models.TextField(default='', max_length=50)),
                ('descr', models.TextField(default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Investor',
            },
        ),
        migrations.CreateModel(
            name='tInvestorContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=50)),
                ('surname', models.TextField(default='', max_length=50)),
                ('midname', models.TextField(default='', max_length=50)),
                ('phone', models.TextField(default='', max_length=15)),
                ('mail', models.TextField(default='', max_length=50)),
                ('position', models.TextField(default='', max_length=50)),
                ('company', models.TextField(default='', max_length=50)),
                ('investorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tInvestor')),
            ],
            options={
                'verbose_name': 'Investors contacts',
            },
        ),
        migrations.CreateModel(
            name='tKeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='tKeyWordToProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Tags to Project',
            },
        ),
        migrations.CreateModel(
            name='tMentoproj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Mentor to Project',
            },
        ),
        migrations.CreateModel(
            name='tMentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=50)),
                ('surname', models.TextField(default='', max_length=50)),
                ('midname', models.TextField(default='', max_length=50)),
                ('phone', models.TextField(default='', max_length=15)),
                ('mail', models.TextField(default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Mentor',
            },
        ),
        migrations.CreateModel(
            name='tProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=50)),
                ('sector', models.TextField(default='', max_length=50)),
                ('descr', models.TextField(default='', max_length=500)),
                ('mentor', models.TextField(default='', max_length=80)),
                ('type', models.TextField(default='', max_length=50)),
                ('isreal', models.TextField(default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Project',
            },
        ),
        migrations.CreateModel(
            name='tStartuper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=50)),
                ('surname', models.TextField(default='', max_length=50)),
                ('midname', models.TextField(default='', max_length=50)),
                ('phone', models.TextField(default='', max_length=15)),
                ('mail', models.TextField(default='', max_length=50)),
                ('avatar', models.ImageField(default='', upload_to='files/imgs/avatars/')),
                ('fgrade', models.BooleanField(default=False)),
                ('sgrade', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Startupers',
            },
        ),
        migrations.CreateModel(
            name='tStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField(default='', max_length=50)),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tProject')),
            ],
            options={
                'verbose_name': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='tTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(default='', max_length=50)),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tProject')),
                ('startuperID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tStartuper')),
            ],
            options={
                'verbose_name': 'Startuper to Project',
            },
        ),
        migrations.AddField(
            model_name='tproject',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tStartuper'),
        ),
        migrations.AddField(
            model_name='tmentoproj',
            name='mentorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tMentor'),
        ),
        migrations.AddField(
            model_name='tmentoproj',
            name='projectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tProject'),
        ),
        migrations.AddField(
            model_name='tkeywordtoproject',
            name='projectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tProject'),
        ),
        migrations.AddField(
            model_name='tkeywordtoproject',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tKeyWord'),
        ),
        migrations.AddField(
            model_name='tinvestition',
            name='investorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tInvestor'),
        ),
        migrations.AddField(
            model_name='tinvestition',
            name='projectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tProject'),
        ),
        migrations.AddField(
            model_name='tdoc',
            name='startuperID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tStartuper'),
        ),
        migrations.AddField(
            model_name='taddinfoproj',
            name='projectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tProject'),
        ),
        migrations.AddField(
            model_name='taddinfoinv',
            name='investorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tInvestor'),
        ),
        migrations.AddField(
            model_name='tactivities',
            name='projectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tProject'),
        ),
    ]
