# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tActProj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '\u041c\u0456\u0441\u0442 \u0417\u0430\u0445\u043e\u0434\u0438-\u041f\u0440\u043e\u0435\u043a\u0442\u0438',
            },
        ),
        migrations.AlterModelOptions(
            name='tactivities',
            options={'verbose_name_plural': '\u0417\u0430\u0445\u043e\u0434\u0438'},
        ),
        migrations.AlterModelOptions(
            name='taddinfoinv',
            options={'verbose_name_plural': '\u0414\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0430 \u0456\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0456\u044f \u043f\u043e \u0456\u043d\u0432\u0435\u0441\u0442\u043e\u0440\u0430\u043c'},
        ),
        migrations.AlterModelOptions(
            name='taddinfoproj',
            options={'verbose_name_plural': '\u0414\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0430 \u0456\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0456\u044f \u043f\u043e \u043f\u0440\u043e\u0435\u043a\u0442\u0430\u043c'},
        ),
        migrations.AlterModelOptions(
            name='tdoc',
            options={'verbose_name_plural': '\u0414\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0430 \u0456\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0456\u044f \u043f\u043e \u0441\u0442\u0430\u0440\u0442\u0430\u043f\u0435\u0440\u0430\u043c'},
        ),
        migrations.AlterModelOptions(
            name='tinvestition',
            options={'verbose_name_plural': '\u0406\u043d\u0432\u0435\u0441\u0442\u0438\u0446\u0456\u0457'},
        ),
        migrations.AlterModelOptions(
            name='tinvestor',
            options={'verbose_name_plural': '\u0406\u043d\u0432\u0435\u0441\u0442\u043e\u0440\u0438'},
        ),
        migrations.AlterModelOptions(
            name='tinvestorcontacts',
            options={'verbose_name_plural': '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u0438 \u0456\u043d\u0432\u0435\u0441\u0442\u043e\u0440\u0456\u0432'},
        ),
        migrations.AlterModelOptions(
            name='tkeyword',
            options={'verbose_name_plural': '\u0422\u0435\u0433\u0438'},
        ),
        migrations.AlterModelOptions(
            name='tkeywordtoproject',
            options={'verbose_name': '\u041c\u0456\u0441\u0442 \u0422\u0435\u0433\u0438-\u041f\u0440\u043e\u0435\u043a\u0442\u0438'},
        ),
        migrations.AlterModelOptions(
            name='tmentoproj',
            options={'verbose_name_plural': '\u041c\u0456\u0441\u0442 \u041c\u0435\u043d\u0442\u043e\u0440\u0438-\u041f\u0440\u043e\u0435\u043a\u0442\u0438'},
        ),
        migrations.AlterModelOptions(
            name='tmentor',
            options={'verbose_name_plural': '\u041c\u0435\u043d\u0442\u043e\u0440\u0438'},
        ),
        migrations.AlterModelOptions(
            name='tproject',
            options={'verbose_name_plural': '\u041f\u0440\u043e\u0435\u043a\u0442\u0438'},
        ),
        migrations.AlterModelOptions(
            name='tschool',
            options={'verbose_name_plural': '\u0428\u043a\u043e\u043b\u0438'},
        ),
        migrations.AlterModelOptions(
            name='tstartuper',
            options={'verbose_name_plural': '\u0421\u0442\u0430\u0440\u0442\u0430\u043f\u0435\u0440\u0438'},
        ),
        migrations.AlterModelOptions(
            name='tstatus',
            options={'verbose_name_plural': '\u0421\u0442\u0430\u0442\u0443\u0441\u0438'},
        ),
        migrations.AlterModelOptions(
            name='tteam',
            options={'verbose_name_plural': '\u041c\u0456\u0441\u0442 \u0421\u0442\u0430\u0440\u0442\u0430\u043f\u0435\u0440\u0438-\u041f\u0440\u043e\u0435\u043a\u0442\u0438'},
        ),
        migrations.AlterModelOptions(
            name='tusersch',
            options={'verbose_name': '\u0428\u043a\u043e\u043b\u0430', 'verbose_name_plural': '\u0428\u043a\u043e\u043b\u0430'},
        ),
        migrations.RemoveField(
            model_name='tactivities',
            name='projectID',
        ),
        migrations.AddField(
            model_name='tactproj',
            name='eventID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tActivities'),
        ),
        migrations.AddField(
            model_name='tactproj',
            name='projectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tProject'),
        ),
    ]
