# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tactivities',
            name='title',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='taddinfoinv',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='files/investors/'),
        ),
        migrations.AlterField(
            model_name='tdoc',
            name='title',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tinvestor',
            name='investor',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tinvestorcontacts',
            name='name',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tinvestorcontacts',
            name='surname',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tmentor',
            name='name',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tmentor',
            name='surname',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tproject',
            name='title',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tschool',
            name='city',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tstartuper',
            name='name',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tstartuper',
            name='surname',
            field=models.TextField(default='', max_length=50),
        ),
    ]
