# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 16:50
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161010_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='tactivities',
            name='school',
            field=models.ForeignKey(default=None, on_delete=models.SET(app.models.getDefSchool), to='app.tSchool'),
        ),
    ]
