# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_tproject_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmentoproj',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
