# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161030_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinvestor',
            name='message',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
    ]
