# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tinvestor_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tschool',
            options={'verbose_name_plural': '\u0424\u0456\u043b\u0456\u0430\u043b\u0438'},
        ),
        migrations.AlterModelOptions(
            name='tvisitors',
            options={'verbose_name_plural': '\u0412\u0456\u0434\u0432\u0456\u0434\u0443\u0432\u0430\u0447\u0456 \u0441\u0442\u043e\u0440\u0456\u043d\u043e\u043a \u0437 \u0456\u043d\u0432\u0435\u0441\u0442\u043e\u0440\u0430\u043c\u0438'},
        ),
        migrations.AddField(
            model_name='tschool',
            name='contacts',
            field=models.TextField(default='', max_length=500),
        ),
    ]
