# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160824_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmentoproj',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
