# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160824_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tactivities',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tdoc',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tinvestition',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tmentoproj',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tstatus',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
