# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160824_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tproject',
            name='leader',
        ),
        migrations.AddField(
            model_name='tteam',
            name='islead',
            field=models.BooleanField(default=False),
        ),
    ]
