# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160828_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='tReqInvests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', models.TextField(default='', max_length=50)),
                ('sum', models.TextField(default='', max_length=15)),
                ('type', models.TextField(default='', max_length=50)),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tProject')),
            ],
        ),
        migrations.AlterModelOptions(
            name='tstartuper',
            options={'verbose_name': 'Startuper'},
        ),
        migrations.AddField(
            model_name='tinvestition',
            name='res',
            field=models.TextField(default='', max_length=50),
        ),
    ]
