# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160904_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treqinvests',
            name='projectID',
        ),
        migrations.AddField(
            model_name='tproject',
            name='financeScale',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tproject',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tstartuper',
            name='finyear',
            field=models.TextField(default='2000', max_length=5),
        ),
        migrations.DeleteModel(
            name='tReqInvests',
        ),
    ]
