# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160911_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tstartuper',
            name='finyear',
            field=models.TextField(default='-', max_length=5),
        ),
    ]
